# .github/workflows/ht-bodega-info.yaml
name: ht-bodega-info
on: 
  # push:
  workflow_dispatch:
  # repository_dispatch:
  #  types: [ht-bodega-info]

jobs:
  ht-data-validator:
    runs-on: ubuntu-latest
    environment: ht-actions
    name: ht-bodega-info
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: 'plindman/ht-actions'
          path: ''
          token: ${{ secrets.HT_ACTIONS_CODE }}

      - name: Checkout ht-product-info
        uses: actions/checkout@v3
        with:
          repository: plindman/ht-bodega-info
          path: src/ht-product-info
          token: ${{ secrets.HT_ACTIONS_CODE }}

      - name: Run the action
        id: ht-bodega-info
        uses: ./src/ht-bodega-info/
        with:
          MSGRAPH_URL: ${{ vars.MSGRAPH_URL }}
          MSGRAPH_SCOPE: ${{ vars.MSGRAPH_SCOPE }}
          MSGRAPH_AUTHORITY: ${{ vars.MSGRAPH_AUTHORITY }}

          MSGRAPH_CLIENT_ID: ${{ secrets.MSGRAPH_CLIENT_ID }}
          MSGRAPH_CLIENT_SECRET: ${{ secrets.MSGRAPH_CLIENT_SECRET }}
          MSGRAPH_TENANT_ID: ${{ secrets.MSGRAPH_TENANT_ID }}

          HT_SHAREPOINT_HOST: ${{ vars.HT_SHAREPOINT_HOST }}
          HT_SHAREPOINT_SITE: ${{ vars.HT_SHAREPOINT_SITE }}
          HT_SHAREPOINT_URL: ${{ vars.HT_SHAREPOINT_URL }}
          HT_SHAREPOINT_DOCS: ${{ vars.HT_SHAREPOINT_DOCS }}

          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
            name: temp logs
            path: |
              temp/*.log
