# .github/workflows/ht-pdf.yaml
name: ht-pdf
on: 
  # push:
  workflow_dispatch:
  repository_dispatch:
    types: [ht-pdf-start]

env:
  SHAREPOINT_USERNAME: ${{ secrets.SHAREPOINT_USERNAME }}
  SHAREPOINT_PASSWORD: ${{ secrets.SHAREPOINT_PASSWORD }}

jobs:
  ht-pdf:
    runs-on: ubuntu-latest
    name: HT pdf processing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone ht-pdf private repository
        uses: actions/checkout@v3
        with:
          repository: 'plindman/ht-pdf'
          token: ${{ secrets.HTPDFREPO }}
          path: ''
      - name: Build the pdfs
        id: generate-pdf-flow
        uses: ./generate-pdf-action/
